// react/src/views/assets/DistrictView.tsx
import ReactECharts from 'echarts-for-react';
import { MapPin, Users, Droplets, ArrowUpDown } from 'lucide-react';

const districts = [
    { id: 1, name: '雨花排水分区', area: '12.5 km²', pipeLength: '486 km', population: '32万', coverage: 95, type: '分流制' },
    { id: 2, name: '海淀排水分区', area: '18.3 km²', pipeLength: '612 km', population: '45万', coverage: 92, type: '分流制' },
    { id: 3, name: '侯家塘排水分区', area: '8.7 km²', pipeLength: '324 km', population: '28万', coverage: 88, type: '合流制' },
    { id: 4, name: '东城排水分区', area: '6.2 km²', pipeLength: '256 km', population: '22万', coverage: 91, type: '合流制' },
    { id: 5, name: '丰台排水分区', area: '22.8 km²', pipeLength: '578 km', population: '38万', coverage: 85, type: '混合制' },
    { id: 6, name: '石景山排水分区', area: '15.1 km²', pipeLength: '391 km', population: '25万', coverage: 93, type: '分流制' },
];

function getChartOption() {
    return {
        backgroundColor: 'transparent',
        tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
        grid: { top: 30, right: 20, bottom: 30, left: 80 },
        xAxis: { type: 'value', name: 'km', axisLabel: { color: '#5A6B7C', fontSize: 10 }, splitLine: { lineStyle: { color: '#1E3348' } } },
        yAxis: { type: 'category', data: districts.map(d => d.name).reverse(), axisLabel: { color: '#8899AA', fontSize: 10 }, axisLine: { lineStyle: { color: '#2A3F54' } } },
        series: [
            { name: '雨水管', type: 'bar', stack: 'total', data: [195, 220, 85, 120, 260, 170].reverse(), itemStyle: { color: '#3B82F6' } },
            { name: '污水管', type: 'bar', stack: 'total', data: [185, 240, 140, 90, 200, 145].reverse(), itemStyle: { color: '#00D4AA' } },
            { name: '合流管', type: 'bar', stack: 'total', data: [106, 152, 99, 46, 118, 76].reverse(), itemStyle: { color: '#FFB020' } },
        ]
    };
}

export default function DistrictView() {
    return (
        <div className="space-y-4 p-4">
            {/* 分区卡片 */}
            <div className="grid grid-cols-3 gap-3">
                {districts.map(d => (
                    <div key={d.id} className="bg-card border border-themed rounded-xl p-4 shadow-themed hover:shadow-themed-md transition-shadow cursor-pointer">
                        <div className="flex items-center justify-between mb-3">
                            <h4 className="text-sm font-semibold text-default">{d.name}</h4>
                            <span className="text-[10px] px-2 py-0.5 rounded-md bg-primary/15 text-primary">{d.type}</span>
                        </div>
                        <div className="grid grid-cols-2 gap-y-2 text-xs">
                            <div className="flex items-center gap-1.5 text-dim"><MapPin className="w-3 h-3" /> {d.area}</div>
                            <div className="flex items-center gap-1.5 text-dim"><Droplets className="w-3 h-3" /> {d.pipeLength}</div>
                            <div className="flex items-center gap-1.5 text-dim"><Users className="w-3 h-3" /> {d.population}</div>
                            <div className="flex items-center gap-1.5 text-dim"><ArrowUpDown className="w-3 h-3" /> 覆盖率 {d.coverage}%</div>
                        </div>
                        <div className="mt-3 flex items-center gap-2">
                            <div className="flex-1 bg-surface rounded-full h-1.5">
                                <div className="h-1.5 rounded-full bg-primary" style={{ width: `${d.coverage}%` }}></div>
                            </div>
                            <span className="text-[10px] text-primary font-medium">{d.coverage}%</span>
                        </div>
                    </div>
                ))}
            </div>

            {/* 管道类型分布图 */}
            <div className="bg-card border border-themed rounded-xl p-4 shadow-themed">
                <h3 className="text-sm font-semibold text-default mb-2">各分区管道类型分布</h3>
                <div className="h-64">
                    <ReactECharts option={getChartOption()} style={{ height: '100%', width: '100%' }} />
                </div>
            </div>
        </div>
    );
}

// src/views/quality/DistrictView.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import * as echarts from 'echarts'
import { MapPin, Layers, BarChart3 } from 'lucide-vue-next'

// 排水分区
const districts = ref([
    { id: 'D-001', name: '朝阳分区', area: 12.5, population: 85000, pipeLength: 45.2, pipeType: '合流制', stormDensity: 3.6, outlets: 8, pumpStations: 1, loadRate: 78 },
    { id: 'D-002', name: '海淀分区', area: 18.3, population: 120000, pipeLength: 62.8, pipeType: '分流制', stormDensity: 3.4, outlets: 12, pumpStations: 2, loadRate: 65 },
    { id: 'D-003', name: '西城分区', area: 8.2, population: 56000, pipeLength: 28.5, pipeType: '合流制', stormDensity: 3.5, outlets: 5, pumpStations: 1, loadRate: 92 },
    { id: 'D-004', name: '东城分区', area: 6.8, population: 48000, pipeLength: 22.3, pipeType: '分流制', stormDensity: 3.3, outlets: 4, pumpStations: 0, loadRate: 55 },
    { id: 'D-005', name: '丰台分区', area: 22.1, population: 95000, pipeLength: 58.6, pipeType: '混合制', stormDensity: 2.7, outlets: 10, pumpStations: 1, loadRate: 70 },
])

const chartRef = ref<HTMLElement>()
let chart: echarts.ECharts | null = null

onMounted(() => {
    if (chartRef.value) {
        chart = echarts.init(chartRef.value)
        chart.setOption({
            backgroundColor: 'transparent',
            tooltip: { trigger: 'axis' },
            legend: { top: 0, textStyle: { color: '#8899AA', fontSize: 10 } },
            grid: { top: 30, right: 15, bottom: 30, left: 45 },
            xAxis: { type: 'category', data: districts.value.map(d => d.name), axisLabel: { color: '#5A6B7C', fontSize: 10 }, axisLine: { lineStyle: { color: '#2A3F54' } } },
            yAxis: [
                { type: 'value', name: 'km', nameTextStyle: { color: '#5A6B7C' }, axisLabel: { color: '#5A6B7C', fontSize: 10 }, splitLine: { lineStyle: { color: '#1E3348' } } },
                { type: 'value', name: '%', nameTextStyle: { color: '#5A6B7C' }, max: 100, axisLabel: { color: '#5A6B7C', fontSize: 10 }, splitLine: { show: false } },
            ],
            series: [
                { name: '管网长度(km)', type: 'bar', data: districts.value.map(d => d.pipeLength), itemStyle: { color: '#3B82F6', borderRadius: [3, 3, 0, 0] } },
                { name: '负载率(%)', type: 'line', yAxisIndex: 1, data: districts.value.map(d => d.loadRate), lineStyle: { color: '#FFB020' }, itemStyle: { color: '#FFB020' } },
            ]
        })
        window.addEventListener('resize', () => chart?.resize())
    }
})

onUnmounted(() => { chart?.dispose() })
</script>

<template>
    <div class="space-y-4">
        <div class="bg-card border border-themed rounded-xl shadow-themed overflow-hidden">
            <table class="w-full text-sm">
                <thead>
                    <tr class="border-b border-themed">
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">分区名称</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">面积(km²)</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">服务人口</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">管网(km)</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">排水体制</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">管网密度</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">排放口</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">泵站</th>
                        <th class="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">负载率</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="d in districts" :key="d.id"
                        class="border-b border-themed/50 hover:bg-hover-themed transition-colors">
                        <td class="px-4 py-2.5 text-xs font-medium text-primary">{{ d.name }}</td>
                        <td class="px-4 py-2.5 text-xs text-default">{{ d.area }}</td>
                        <td class="px-4 py-2.5 text-xs text-default">{{ d.population.toLocaleString() }}</td>
                        <td class="px-4 py-2.5 text-xs text-default">{{ d.pipeLength }}</td>
                        <td class="px-4 py-2.5"><span class="text-[10px] px-2 py-0.5 rounded-md"
                                :class="d.pipeType === '分流制' ? 'bg-success/15 text-success' : d.pipeType === '合流制' ? 'bg-warning/15 text-warning' : 'bg-info/15 text-info'">{{
                                d.pipeType }}</span></td>
                        <td class="px-4 py-2.5 text-xs text-dim">{{ d.stormDensity }} km/km²</td>
                        <td class="px-4 py-2.5 text-xs text-default">{{ d.outlets }}</td>
                        <td class="px-4 py-2.5 text-xs text-default">{{ d.pumpStations }}</td>
                        <td class="px-4 py-2.5">
                            <div class="flex items-center gap-2">
                                <div class="w-14 bg-surface rounded-full h-1.5">
                                    <div class="h-1.5 rounded-full"
                                        :class="d.loadRate > 85 ? 'bg-danger' : d.loadRate > 70 ? 'bg-warning' : 'bg-success'"
                                        :style="{ width: d.loadRate + '%' }"></div>
                                </div>
                                <span class="text-[10px]" :class="d.loadRate > 85 ? 'text-danger' : 'text-dim'">{{
                                    d.loadRate }}%</span>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="bg-card border border-themed rounded-xl p-4 shadow-themed">
            <h4 class="text-sm font-semibold text-default mb-2">分区管网概况</h4>
            <div ref="chartRef" class="h-52"></div>
        </div>
    </div>
</template>
