// react/src/views/monitoring/DevicesView.tsx
import { Wifi, WifiOff, Battery, Eye } from 'lucide-react';

const devices = [
    { id: 'DEV-001', name: '雨花路流量计', type: '电磁流量计', location: '雨花路DN600', status: 'online', battery: 95, signal: 'strong', lastData: '刚刚' },
    { id: 'DEV-002', name: '民生路液位计', type: '超声波液位计', location: '民生路DN400', status: 'online', battery: 82, signal: 'medium', lastData: '2分钟前' },
    { id: 'DEV-003', name: '和平路雨量计', type: '翻斗式雨量计', location: '和平路雨量站', status: 'online', battery: 67, signal: 'strong', lastData: '5分钟前' },
    { id: 'DEV-004', name: '新华街流量计', type: '电磁流量计', location: '新华街DN800', status: 'warning', battery: 23, signal: 'weak', lastData: '30分钟前' },
    { id: 'DEV-005', name: '东湖泵站传感器组', type: '多参数传感器', location: '东湖泵站', status: 'online', battery: 100, signal: 'strong', lastData: '刚刚' },
    { id: 'DEV-006', name: '侯家塘区水质仪', type: '在线水质分析仪', location: '侯家塘区进水口', status: 'offline', battery: 0, signal: 'none', lastData: '3天前' },
    { id: 'DEV-007', name: '丰台路液位计', type: '压力式液位计', location: '丰台路DN500', status: 'online', battery: 88, signal: 'strong', lastData: '1分钟前' },
    { id: 'DEV-008', name: '建设大道视频', type: '智能摄像头', location: '建设大道排放口', status: 'online', battery: 100, signal: 'medium', lastData: '刚刚' },
];

function getStatusColor(s: string) { return s === 'online' ? 'bg-success' : s === 'warning' ? 'bg-warning' : 'bg-danger'; }
function getStatusText(s: string) { return s === 'online' ? '在线' : s === 'warning' ? '异常' : '离线'; }
function getBatteryColor(b: number) { return b > 60 ? 'text-success' : b > 25 ? 'text-warning' : 'text-danger'; }

export default function DevicesView() {
    const onlineCount = devices.filter(d => d.status === 'online').length;
    const warningCount = devices.filter(d => d.status === 'warning').length;
    const offlineCount = devices.filter(d => d.status === 'offline').length;
    return (
        <div className="space-y-4 p-4">
            <div className="grid grid-cols-4 gap-3">
                <div className="bg-card border border-themed rounded-lg p-3 shadow-themed text-center"><p className="text-2xl font-bold text-default">{devices.length}</p><p className="text-xs text-dim">设备总数</p></div>
                <div className="bg-card border border-themed rounded-lg p-3 shadow-themed text-center"><p className="text-2xl font-bold text-success">{onlineCount}</p><p className="text-xs text-dim">在线</p></div>
                <div className="bg-card border border-themed rounded-lg p-3 shadow-themed text-center"><p className="text-2xl font-bold text-warning">{warningCount}</p><p className="text-xs text-dim">异常</p></div>
                <div className="bg-card border border-themed rounded-lg p-3 shadow-themed text-center"><p className="text-2xl font-bold text-danger">{offlineCount}</p><p className="text-xs text-dim">离线</p></div>
            </div>
            <div className="bg-card border border-themed rounded-xl shadow-themed overflow-hidden">
                <table className="w-full text-sm">
                    <thead><tr className="border-b border-themed">
                        {['设备状态', '设备名称', '类型', '位置', '电量', '信号', '最后数据', '操作'].map(h => (
                            <th key={h} className="text-left px-4 py-3 text-xs font-semibold text-dim bg-surface">{h}</th>
                        ))}
                    </tr></thead>
                    <tbody>
                        {devices.map(d => (
                            <tr key={d.id} className="border-b border-themed/50 hover:bg-hover-themed transition-colors">
                                <td className="px-4 py-2.5"><span className="flex items-center gap-1.5"><span className={`w-2 h-2 rounded-full ${getStatusColor(d.status)}`}></span><span className="text-[10px]">{getStatusText(d.status)}</span></span></td>
                                <td className="px-4 py-2.5"><p className="text-xs font-medium text-default">{d.name}</p><p className="text-[10px] text-muted-themed font-mono">{d.id}</p></td>
                                <td className="px-4 py-2.5 text-xs text-dim">{d.type}</td>
                                <td className="px-4 py-2.5 text-xs text-dim">{d.location}</td>
                                <td className="px-4 py-2.5"><div className="flex items-center gap-1.5"><Battery className={`w-3.5 h-3.5 ${getBatteryColor(d.battery)}`} /><span className={`text-xs ${getBatteryColor(d.battery)}`}>{d.battery}%</span></div></td>
                                <td className="px-4 py-2.5">{d.signal !== 'none' ? <Wifi className={`w-3.5 h-3.5 ${d.signal === 'strong' ? 'text-success' : d.signal === 'medium' ? 'text-warning' : 'text-danger'}`} /> : <WifiOff className="w-3.5 h-3.5 text-danger" />}</td>
                                <td className="px-4 py-2.5 text-xs text-dim">{d.lastData}</td>
                                <td className="px-4 py-2.5"><button className="p-1 rounded hover:bg-primary/10 text-primary transition-colors cursor-pointer"><Eye className="w-3.5 h-3.5" /></button></td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

// src/views/dashboard/DevicesView.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Radio, Target } from 'lucide-vue-next'

const activeFunc = ref('equip')
const funcTabs = [{ key: 'equip', label: '监测设备统计' }, { key: 'object', label: '监测对象统计' }]

const equipStats = ref([
    { type: '流量设备', total: 85, online: 80, offline: 5, rate: 94.1 },
    { type: '液位设备', total: 62, online: 58, offline: 4, rate: 93.5 },
    { type: '水质设备', total: 28, online: 25, offline: 3, rate: 89.3 },
    { type: '降雨设备', total: 35, online: 34, offline: 1, rate: 97.1 },
])
const objectStats = ref([
    { type: '管道', count: 1125, monitored: 85, coverage: 7.6 },
    { type: '排放口', count: 40, monitored: 28, coverage: 70.0 },
    { type: '闸门', count: 26, monitored: 18, coverage: 69.2 },
    { type: '污水处理厂', count: 5, monitored: 5, coverage: 100 },
    { type: '河道', count: 12, monitored: 8, coverage: 66.7 },
    { type: '易涝点', count: 18, monitored: 15, coverage: 83.3 },
])
</script>

<template>
    <div class="space-y-4">
        <div class="flex items-center gap-0.5 bg-card border border-themed rounded-lg p-0.5">
            <button v-for="ft in funcTabs" :key="ft.key" @click="activeFunc = ft.key"
                class="px-2.5 py-1.5 rounded-md text-[11px] font-medium transition-colors cursor-pointer whitespace-nowrap"
                :class="activeFunc === ft.key ? 'bg-primary text-white' : 'text-dim hover:text-default hover:bg-hover-themed'">{{
                ft.label }}</button>
        </div>
        <template v-if="activeFunc === 'equip'">
            <div class="flex items-center gap-2 mb-1">
                <Radio class="w-4 h-4 text-primary" /><span class="text-sm font-semibold text-default">监测设备统计</span>
            </div>
            <div class="grid grid-cols-4 gap-3 mb-3">
                <div v-for="e in equipStats" :key="e.type"
                    class="bg-card border border-themed rounded-xl shadow-themed p-4 text-center">
                    <p class="text-[10px] text-dim mb-1">{{ e.type }}</p>
                    <p class="text-2xl font-bold text-primary">{{ e.total }}</p>
                    <div class="flex justify-center gap-3 mt-1 text-[10px]"><span class="text-success">在线 {{ e.online
                            }}</span><span class="text-danger">离线 {{ e.offline }}</span></div>
                    <div class="w-full h-1.5 bg-surface rounded-full mt-2 overflow-hidden">
                        <div class="h-full bg-success rounded-full" :style="{ width: e.rate + '%' }"></div>
                    </div>
                    <p class="text-[10px] text-success mt-1">在线率 {{ e.rate }}%</p>
                </div>
            </div>
        </template>
        <template v-if="activeFunc === 'object'">
            <div class="flex items-center gap-2 mb-1">
                <Target class="w-4 h-4 text-primary" /><span class="text-sm font-semibold text-default">监测对象统计</span>
            </div>
            <div class="bg-card border border-themed rounded-xl shadow-themed overflow-hidden">
                <table class="w-full text-xs">
                    <thead>
                        <tr class="border-b border-themed bg-surface/50">
                            <th class="text-left px-3 py-2.5 text-dim font-medium">对象类型</th>
                            <th class="text-center px-2 py-2.5 text-dim font-medium">总数</th>
                            <th class="text-center px-2 py-2.5 text-dim font-medium">已监测</th>
                            <th class="text-center px-2 py-2.5 text-dim font-medium">覆盖率</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="o in objectStats" :key="o.type"
                            class="border-b border-themed/30 hover:bg-hover-themed">
                            <td class="px-3 py-2.5 text-default font-medium">{{ o.type }}</td>
                            <td class="text-center px-2 py-2.5 text-default">{{ o.count }}</td>
                            <td class="text-center px-2 py-2.5 text-primary font-bold">{{ o.monitored }}</td>
                            <td class="text-center px-2 py-2.5">
                                <div class="flex items-center justify-center gap-1">
                                    <div class="w-12 h-2 bg-surface rounded-full overflow-hidden">
                                        <div class="h-full rounded-full"
                                            :class="o.coverage >= 80 ? 'bg-success' : o.coverage >= 50 ? 'bg-warning' : 'bg-danger'"
                                            :style="{ width: o.coverage + '%' }"></div>
                                    </div><span class="text-[10px] font-bold"
                                        :class="o.coverage >= 80 ? 'text-success' : o.coverage >= 50 ? 'text-warning' : 'text-danger'">{{
                                        o.coverage }}%</span>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </template>
    </div>
</template>
